['.config/nvim']
type = 'git-repo'
url = "https://github.com/arunim-io/neovim-config"
refreshPeriod = '168h'

['.config/tmux/plugins/tpm']
type = 'git-repo'
url = 'https://github.com/tmux-plugins/tpm'
refreshPeriod = '24h'

['.config/wallpapers']
type = 'git-repo'
url = "https://github.com/arunim-io/wallpapers"
refreshPeriod = '24h'
